config/routes.rb
Rails.application.routes.draw do
  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  resources :users

  resources :categories
  resources :posts do
  	resources :comments
  end

  root 'posts#index'
  get '/about' => 'posts#about'
  get '/services' => 'posts#services'
  get '/contact' => 'posts#contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts

	validates :name, :presence => true, :length => {:minimum => 3}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :comments

  mount_uploader :image, ImageUploader

  validates :name, :presence => true
  validates :title, :presence => true, :length => {:minimum => 3}
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def require_user
		redirect_to 'login' unless current_user
	end

  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create, :update, :edit, :destroy]
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @posts = @category.posts.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(comment_params)
		if @comment.save
			redirect_to post_path(@post)
			flash[:notice] = "Comment Added!"
		else
			redirect_to post_path(@post)
			flash[:notice] = "Comment Added!"
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:commenter, :body)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user, only: [:new, :create, :update, :edit, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def about
  end

  def services
  end

  def contact
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :title, :body, :image, :category_id)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new    
    render layout: 'signup'
  end

  def create
  	@user = User.find_by_email(params[:session][:email])
  	if @user && @user.authenticate(params[:session][:password])
  		session[:user_id] = @user.id
  		redirect_to '/'
  	else
  		redirect_to '/login'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  	render layout: 'signup'
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		session[:user_id] = @user.id
  		redirect_to '/'
  	else
  		redirect_to '/signup'
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "col-sm-2 control-label" %>
    <%= form.text_field :name, id: :category_name, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="col-lg-8">
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-lg-8">
<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
      <% if current_user %>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<hr>
<% if current_user %>
<%= link_to 'New Category', new_category_path %>
<hr>
<% end %>

app/views/categories/new.html.erb
<div class="col-lg-8">
<h1>New Category</h1>

<%= render 'form', category: @category %>
<hr>
<%= link_to 'Back', categories_path %>
<hr>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4"><%= @category.name %>
            <% if current_user %>
            <small><%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %></small>
            <% end %>
          </h1>
<hr>
<% if current_user %>
          <%= link_to 'New Post', new_post_path %>
<hr>
<% end %>

          <!-- Blog Post -->
          <% @posts.each do |post| %>
          <div class="card mb-4">
            <%= image_tag post.image, class: "card-img-top" %>
            <div class="card-body">
              <h2 class="card-title"><%= post.title %></h2>
              <p class="card-text"><%= post.body %></p>
              <%= link_to "Read More", post, class: "btn btn-primary" %>
            </div>
            <div class="card-footer text-muted">
              Posted on <%= post.created_at.to_s(:long) %> by
              <%= link_to post.name, "#" %>
            </div>
            <% if current_user %>
            <div class="card-footer text-muted">
              <table>
                  <tr>
                    <td><%= link_to 'Edit', edit_post_path(post) %></td>
                    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
              </table>
            </div>
            <% end %>
          </div>
          <% end %>

           <!-- Pagination -->
          <ul class="pagination justify-content-center mb-4">
            <li class="page-item">
              <a class="page-link" href="#">&larr; Older</a>
            </li>
            <li class="page-item disabled">
              <a class="page-link" href="#">Newer &rarr;</a>
            </li>
          </ul>

        




  

app/views/comments/_comment.html.erb
<div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            <div class="media-body">
              <h5 class="mt-0"><%= comment.commenter %></h5>
              <%= comment.body %>
            </div>
          </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XLikeMalcolm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">XLikeMalcolm</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to "Home", "/", class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "About", about_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Services", services_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Contact", contact_path, class: "nav-link" %>
            </li>
          </ul>
          <% if current_user %>
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle btn-sm" type="button" data-toggle="dropdown"><%= current_user.email %><span class="caret"></span></button>
              <ul class="dropdown-menu">
              <li class="nav-item">
                <%= link_to "Profile", contact_path, class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", logout_path, method: "delete", class: "nav-link" %>
              </li>
              </ul>
            </div>
          <% else %>
          <div>
            <%= link_to "Login", login_path, class: "btn btn-success btn-sm" %>
            <%= link_to "Signup", signup_path, class: "btn btn-primary btn-sm" %>
          </div>
          <% end %>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <div class="row">

    <%= yield %>

         

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                	<% Category.all.each do |category| %>
                  <ul class="list-unstyled mb-0">
                    <li>
                      <%= link_to category.name, category_path(category.id) %>
                    </li>
                    <% end %>
                  </ul>
                  <% if current_user %>
                  <hr>
                  <%= link_to 'New Category', new_category_path%>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Side Widget</h5>
            <div class="card-body">
              You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>
  </body>
</html>

app/views/layouts/signup.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XLikeMalcolm</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="login-bg">
  	<!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">XLikeMalcolm</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
      </div>
    </nav>

  <%= yield %>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "col-sm-2 control-label" %>
    <%= form.text_field :name, id: :post_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :title, class: "col-sm-2 control-label" %>
    <%= form.text_field :title, id: :post_title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :body, class: "col-sm-2 control-label" %>
    <%= form.text_area :body, id: :post_body, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image, class: "col-sm-2 control-label" %>
    <%= form.file_field :image, id: :post_image, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :category_id, class: "col-sm-2 control-label" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, class: "btn btn-info dropdown-toggle" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/about.html.erb
<!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">About MyBlog</h1>

          <!-- Post Content -->
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in
              <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

          <hr>

app/views/posts/contact.html.erb
<!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">Contact Us</h1>

          <!-- Post Content -->
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in
              <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

          <hr>

app/views/posts/edit.html.erb
 <div class="col-lg-8">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">MyBlog
            <small>I write what I like</small>
          </h1>
<hr>
<% if current_user %>
          <%= link_to 'New Post', new_post_path %>
<hr>
<% end %>

          <!-- Blog Post -->
          <% @posts.reverse.each do |post| %>
          <div class="card mb-4">
            <%= image_tag post.image, class: "card-img-top" %>
            <div class="card-body">
              <h2 class="card-title"><%= post.title %></h2>
              <p class="card-text"><%= post.body %></p>
              <%= link_to "Read More", post, class: "btn btn-primary" %>
            </div>
            <div class="card-footer text-muted">
              Posted on <%= post.created_at.to_s(:long) %> by
              <%= link_to post.name, "#" %>
            </div>
            <% if current_user %>
            <div class="card-footer text-muted">
              <table>
                  <tr>
                    <td><%= link_to 'Edit', edit_post_path(post) %></td>
                    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                  </tr>
              </table>
            </div>
            <% end %>
          </div>
          <% end %>

          
 <!-- Pagination -->
          <ul class="pagination justify-content-center mb-4">
            <li class="page-item">
              <a class="page-link" href="#">&larr; Older</a>
            </li>
            <li class="page-item disabled">
              <a class="page-link" href="#">Newer &rarr;</a>
            </li>
          </ul>
        




  

app/views/posts/new.html.erb
 <div class="col-lg-8">
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/services.html.erb
<!-- Post Content Column -->
        <div class="col-lg-8">

          <!-- Title -->
          <h1 class="mt-4">My Services</h1>

          <!-- Post Content -->
          <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero, obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi eos magni recusandae laborum minus inventore?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat. Temporibus, voluptatibus.</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat perspiciatis. Enim, iure!</p>

          <blockquote class="blockquote">
            <p class="mb-0">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer posuere erat a ante.</p>
            <footer class="blockquote-footer">Someone famous in
              <cite title="Source Title">Source Title</cite>
            </footer>
          </blockquote>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem obcaecati?</p>

          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo, aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam recusandae? Qui, necessitatibus, est!</p>

          <hr>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<!-- Post Content Column -->
        <div class="col-lg-8">
<p id="notice"><%= notice %></p>
          <% if current_user %>
          <%= link_to 'Edit', edit_post_path(@post) %> | <%= link_to 'Back', posts_path %>
          <% end %>
          <!-- Title -->
          <h1 class="mt-4"><%= @post.title %></h1>

          <!-- Author -->
          <p class="lead">
            by
            <%= link_to @post.name, "#" %>
          </p>

          <hr>

          <!-- Date/Time -->
          <p>Posted on <%= @post.created_at.to_s(:long) %></p>

          <hr>

          <!-- Preview Image -->
          <%= image_tag @post.image, class: "img-fluid rounded" %>

          <hr>

          <!-- Post Content -->
          <p><%= @post.body %></p>

          <hr>

          <!-- Comments Form -->
          <div class="card my-4">
            <h5 class="card-header">Leave a Comment:</h5>
            <div class="card-body">
              <%= form_for([@post, @post.comments.build]) do |f| %>
                <div class="form-group">
                  <%= f.text_field :commenter, :placeholder => "Name", class: "form-control" %>
                </div>
                <div class="form-group">
                  <%= f.text_area :body, :placeholder => "Enter comment here", class: "form-control" %>
                </div>
                <%= f.submit class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>

          <!-- Single Comment -->
          <%= render @post.comments %>

app/views/users/new.html.erb
<div class="row text-center">
	<div  class="col-lg-4 offset4">
	</div>
	<div class="col-lg-4 offset4">
        <h3>Sign Up</h3>
        <%= form_for (@user) do |f| %>
        <div class="form-group">
        <%= f.text_field :first_name, :placeholder => "First Name", class: "form-control" %>
    	</div>
    	<div class="form-group">
        <%= f.text_field :last_name, :placeholder => "Last Name", class: "form-control" %>
    	</div>
        <div class="form-group">
        <%= f.text_field :email, :placeholder => "E-mail", class: "form-control" %>
        </div>
        <div class="form-group">
        <%= f.password_field :password, :placeholder => "Password", class: "form-control" %>
    	</div>
        <div class="form-group">
            <%= f.submit "Create Account", class: "btn btn-primary signup" %>
        </div>
        <% end %> 
    </div>
</div>